name: Deploy React (Vite) App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install sshpass & rsync
        run: sudo apt-get update && sudo apt-get install -y sshpass rsync

      - name: Deploy dist folder to VPS
        run: |
          # Ensure Todo directory exists
          sshpass -p "${{ secrets.VPS_PASS }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p /root/web/Todo"

          # Copy dist folder (replace old one completely)
          rsync -avz --delete \
            -e "sshpass -p '${{ secrets.VPS_PASS }}' ssh -o StrictHostKeyChecking=no" \
            dist/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/root/web/Todo/dist